### ISSUE TITLE
ImportError: cannot import name 'utc' from 'django.utils.timezone'

### ISSUE THREAD

**Issue by pkrakesh** [xurble/django-feed-reader#26]
ImportError: cannot import name 'utc' from 'django.utils.timezone' at`from django.utils.timezone import utc`. 
Using Python 3.11.2 and Django 5.0.1

**Comment by bruvellu** [comment]
Got the same error, but works with Django 4.2.9

**Comment by xurble** [comment]
Fixed in 1.0.8
